<style>
    .btn-block {
        width: 100%;
    }
</style>
<main class="container-flex">
    <div class="row">
        <div class="s12">

            <table class="responsive-table">
                <tbody>
                <tr>
                    <td width="50%"></td>
                    <td width="20%"></td>
                    <td width="20%"></td>
                    <td width="10%"></td>
                </tr>
                <tr>
                    <td>Usuários</td>
                    <td>
                        <a href="<?= URL ?>/cadastrar" class="waves-effect waves-light btn btn-block"><i class="material-icons left">add</i>Cadastrar</a>
                    </td>
                    <td>
                        <a href="<?= URL ?>/user/gerenciar" class="waves-effect waves-light btn btn-block"><i class="material-icons left">settings_applications</i>Gerenciar</a>
                    </td>
                    <td></td>
                </tr>
                <tr>
                    <td>Assuntos</td>
                    <td>
                        <a href="<?= URL ?>/assunto/cadastrar" class="waves-effect waves-light btn btn-block"><i class="material-icons left">add</i>Cadastrar</a>
                    </td>
                    <td>
                        <a href="<?= URL ?>/assunto/gerenciar" class="waves-effect waves-light btn btn-block"><i class="material-icons left">settings_applications</i>Gerenciar</a>
                    </td>
                    <td></td>
                </tr>
                <tr>
                    <td>Bancas</td>
                    <td>
                        <a href="<?= URL ?>/cadastrar" class="waves-effect waves-light btn btn-block"><i class="material-icons left">add</i>Cadastrar</a>
                    </td>
                    <td>
                        <a href="<?= URL ?>/user/gerenciar" class="waves-effect waves-light btn btn-block"><i class="material-icons left">settings_applications</i>Gerenciar</a>
                    </td>
                    <td></td>
                </tr>
                <tr>
                    <td>Questões</td>
                    <td>

                    </td>
                    <td>
                        <a href="<?= URL ?>/user/gerenciar" class="waves-effect waves-light btn btn-block"><i class="material-icons left">settings_applications</i>Gerenciar</a>
                    </td>
                    <td></td>
                </tr>
                </tbody>
            </table>

        </div>
    </div>
</main>






