<main class="container">
    <br><br><br><br>
    <div class="row">
        <div class="col s12 m4 offset-m4">
            <div  id="cardlogin" class="card">
                <div class="card-content">
                    <br><br>
                    <div class="row">
                        <form class="col s12" id="loginForm">
                            <div class="row">
                                <div class="input-field col s12">
                                    <input placeholder="Login" id="login" type="text" name="login">
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <input placeholder="Senha" id="pass" type="password" name="pass">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s6">
                                    <span class="teal-text left-align"><a href="<?= URL ?>/esqueciasenha">Esqueci minha senha!</a></span>
                                </div>
                                <div class="col s6 right-align">
                                    <button type="submit" class="waves-effect waves-light btn">Logar</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</main>

<script>
    $( "#loginForm" ).submit(function( event ) {
        event.preventDefault();
        var $form = $( this ),
            login = $form.find( "input[name='login']" ).val(),
            pass = $form.find( "input[name='pass']" ).val(),
            url = $form.attr( "<?= URL . 'logar' ?>" );

        if ( (login == '') || (pass == '') ) {
            M.toast({html: 'Login e senha devem ser preenchidos!', classes: 'rounded'});
            return false;
        }
        var formData = JSON.stringify({ login: login, pass: pass });
        var posting = $.post( url, formData);
        posting.done(function( data ) {
            if (data.aviso == 'admin') {
                window.location.href = '<?= URL . '/admin' ?>';
            } else if (data.aviso == 'usuário') {
                window.location.href = '<?= URL . '/user/listar' ?>';
            } else {
                M.toast({html: 'Usuário e/ou senha inválidos.', classes: 'rounded'});
            }
        });
    });
</script>