<main class="container-fluid">
    <br><br><br><br>
    <div class="row">
        <div class="col s12 m4 offset-m4">
            <div class="card">
                <div class="card-content">
                    <br><br>
                    <div class="row">
                        <form class="col s12" id="loginForm">
                            <div class="row">
                                <div class="input-field col s12">
                                    <input placeholder="Login" id="login" type="text" name="login">
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <input placeholder="Senha" id="pass" type="password" name="pass">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s6">
                                    <span class="teal-text left-align">Esqueci minha senha!  </span>
                                </div>
                                <div class="col s6 right-align">
                                    <button type="submit" class="waves-effect waves-light btn">Logar</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</main>

<script>
    $( "#loginForm" ).submit(function( event ) {
        event.preventDefault();
        var $form = $( this ),
            login = $form.find( "input[name='login']" ).val(),
            pass = $form.find( "input[name='pass']" ).val(),
            url = $form.attr( "<?= URL . 'logar' ?>" );
        var posting = $.post( url, { login: login, pass: pass } );
        posting.done(function( data ) {
            M.toast({html: data, classes: 'rounded'});
        });
    });
</script>