<nav>
    <div class="nav-wrapper">
        <div class="col s12">
            <a href="#!" class="breadcrumb"> </a>
            <a href="#!" class="breadcrumb">Novo Usuário</a>
        </div>
    </div>
</nav>
<div class="container-fluid">
    <br>
    <div class="row">
        <form class="col s12">
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="Digite um e-mail" id="login" type="text">
                    <label for="login">Login</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <input placeholder="*********" id="pass_01" type="password">
                    <label for="pass_01">Senha</label>
                </div>
                <div class="input-field col s6">
                    <input placeholder="*********" id="pass_02" type="password">
                    <label for="pass_02">Senha</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="Digite seu CPF" id="cpf" type="text">
                    <label for="cpf">CPF</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <select>
                        <option value="" disabled selected>Escolha uma área de interesse</option>
                        <option value="1">Option 1</option>
                        <option value="2">Option 2</option>
                        <option value="3">Option 3</option>
                    </select>
                    <label>Área de Interesse</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="Como deseja ser chamado" id="name" type="text">
                    <label for="name">Nome</label>
                </div>
            </div>
            <p class="right-align"><a class="waves-effect waves-light btn">Cadastrar</a></p>
        </form>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems, options);
    });

    // Or with jQuery

    $(document).ready(function(){
        $('select').formSelect();
    });
</script>