<nav>
    <div class="nav-wrapper">
        <div class="col s12">
            <a href="#!" class="breadcrumb"> </a>
            <a href="#!" class="breadcrumb">Novo Usuário</a>
        </div>
    </div>
</nav>
<div class="container-fluid">
    <br>
    <div class="row">
        <form class="col s12" id="newUser">
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="Digite um e-mail" id="login" type="text" name="login" data-length="100">
                    <label for="login">Login *</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <input placeholder="*********" id="pass_01" type="password" name="pass">
                    <label for="pass_01">Senha *</label>
                </div>
                <div class="input-field col s6">
                    <input placeholder="*********" id="pass_02" type="password">
                    <label for="pass_02">Senha *</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="Digite seu CPF" id="cpf" type="text" name="cpf" onkeyup="var cpf = this.value; if (cpf.match(/^\d{3}$/) !== null) {this.value = cpf + '.';} else if (cpf.match(/^\d{3}\.\d{3}$/) !== null) {this.value = cpf + '.';} else if (cpf.match(/^\d{3}\.\d{3}\.\d{3}$/) !== null) {this.value = cpf + '-';}" data-length="14">
                    <label for="cpf">CPF *</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <select id="area" name="area">
                        <option value="" disabled selected>Escolha uma área de interesse</option>
                    </select>
                    <label>Área de Interesse *</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="Como deseja ser chamado" id="name" type="text" name="name" data-length="150">
                    <label for="name">Nome *</label>
                </div>
            </div>
            <p class="right-align"><button id="salvar" type="submit" class="waves-effect waves-light btn">Cadastrar</button></p>
        </form>
    </div>
</div>

<script>
    $(document).ready(function(){
        $('input#cpf, input#name').characterCounter();
        $.getJSON( '<?= URL ?>/subjects', function( data ) {
            $.each( data, (key , value) => {
                console.log(value.assunto);
                var option = new Option(value.assunto  , value.id)
                $('#area').append(option)
            });
        }).fail(function(err){
            console.log(err)
        }).done(function(){
            $('select').formSelect();
        });
    });

    $ ("#pass_02").focusout(function () {
        if ( $ ("#pass_01").val() !== $ ("#pass_02").val() ) {
            M.toast({html: 'As senhas deve ser as mesmas.', classes: 'rounded'});
        }
    });

    $( "#newUser" ).submit(function( event ) {
        event.preventDefault();
        var $form = $( this ),
            login = $form.find( "input[name='login']" ).val(),
            pass = $form.find( "input[name='pass']" ).val(),
            cpf = $form.find( "input[name='cpf']" ).val(),
            name = $form.find( "input[name='name']" ).val();

        var area = $("#area").find("option:selected").val();

        if ( (login == '') || (pass == '') ) {
            M.toast({html: 'Login e senha devem ser preenchidos!', classes: 'rounded'});
            return false;
        }

        var formData = JSON.stringify({ login: login, pass: pass, cpf: cpf, name: name, area: area });
        var posting = $.post( "<?= URL . '/novo-user' ?>", formData);
        posting.done(function( data ) {
            if (data.aviso == "Registro salvo com sucesso") {
                $("#salvar").addClass(" disabled");
                M.toast({html: data.aviso, classes: 'rounded'});
                setTimeout(function() {
                    window.location.href = "<?= URL ?>/login";
                }, 1000);
            } else {
                M.toast({html: data.aviso, classes: 'rounded'});
            }

        });
    });
</script>