<main class="container-fluid">
    <div class="row">
        <div class="col s12">
            <h1>Título do Site</h1>
        </div>
        <div class="col s12 grey">
            <p class="flow-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin cursus rhoncus leo, sit amet pretium leo suscipit ac. Donec pharetra feugiat dolor, sed vestibulum nibh. Maecenas urna nisl, pretium sed porttitor sed, posuere non enim. Etiam ac risus ullamcorper massa porttitor suscipit. Praesent quis feugiat purus. Sed euismod tempor convallis. Ut laoreet metus nec quam varius, vel auctor mauris eleifend. Suspendisse laoreet semper nulla at maximus. Cras vestibulum id tellus sed dignissim. Praesent in nibh dui. Sed congue fermentum diam sit amet commodo. Maecenas tempus cursus maximus. Nunc fringilla risus nec quam sodales iaculis. Aliquam varius, purus sit amet laoreet placerat, lorem ex semper diam, id lacinia nulla urna ut turpis. Vestibulum condimentum facilisis lacus vitae interdum.</p>
            <p class="flow-text">Pellentesque tempor lorem non faucibus pretium. Duis et nisi eget risus interdum vulputate. Etiam neque metus, aliquam sit amet gravida maximus, tincidunt vel tellus. Fusce eget orci non felis consectetur mattis. Nunc convallis erat nibh, ac feugiat odio posuere id. Aenean eu sapien eget leo aliquam interdum. Suspendisse et diam lectus. Etiam ut congue dolor.</p>
            <p class="flow-text">Praesent eget fringilla ex. Sed eleifend commodo laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque non tincidunt enim. Aenean ornare justo odio, quis pharetra orci feugiat in. Phasellus commodo ac ipsum quis rhoncus. Nunc et massa elit. Proin vestibulum condimentum tincidunt. Aliquam non justo mollis, pulvinar orci non, ultrices augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla libero neque, tristique eu lectus in, efficitur mollis justo. In enim ex, bibendum ac eleifend vitae, laoreet ut quam. Morbi ac lorem convallis, aliquet purus non, rutrum augue. Fusce nulla augue, lacinia et risus vel, commodo tincidunt dolor. In varius dui est, eleifend eleifend lectus bibendum at. Curabitur porta lobortis nisl at facilisis.</p>
        </div>
        <div class="col s12"><br><br></div>
        <div class="col s6">
            <div class="card-content">
                <span class="card-title"><h3>Responda a e estude!</h3></span>
                <p class="flow-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                <br><br>
                <p class="right-align"><span class="teal-text">Criar seu cadastro  </span><a class="btn-floating btn-large waves-effect waves-light red" href="<?= URL . 'cadastrar'?>"><i class="material-icons">add</i></a></p>
            </div>
        </div>
        <div class="col s6">
            <div class="card-content">
                <span class="card-title"><h3>Questões</h3></span>
                <p class="flow-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                <br><br>
            </div>
        </div>
    </div>
</main>

