<main class="container-fluid">
    <div class="row">
        <div class="col s12">
            <h1>Bem vindo a Mandala</h1>
        </div>
        <div class="col s12 grey">
            <p class="flow-text">Fornece um sistema para estudo para provas e concursos.</p>
            <p class="flow-text">Cadastre-se e acesse nosso banco de perguntas e respostas.</p>
            <p class="flow-text">Nosso serviço conta com inúmeros assuntos e diversas bancas com questões de múltipla escolha, verdadeiro e falso.</p>
        </div>
        <div class="col s12"><br><br></div>
        <div class="col s12 l6">
            <div class="card-content">
                <span class="card-title"><h3>Responda a e estude!</h3></span>
                <p class="flow-text">
                    Cadastre-se e tenha acesso ao banco de questões.
                </p>
                <br><br>
                <p class="right-align"><span class="teal-text">Criar seu cadastro  </span><a class="btn-floating btn-large waves-effect waves-light red" href="<?= URL . '/cadastrar'?>"><i class="material-icons">add</i></a></p>
            </div>
        </div>
        <div class="col s12 l6">
            <div class="card-content">
                <span class="card-title"><h3>Questões</h3></span>
                <p class="flow-text">Lorem ipsum</p>
                <br><br>
            </div>
        </div>
    </div>
</main>

