<nav>
    <div class="nav-wrapper">
        <div class="col s12">
            <a href="#!" class="breadcrumb"> </a>
            <a href="#!" class="breadcrumb">Novo Assunto</a>
        </div>
    </div>
</nav>
<div class="container-fluid">
    <br>
    <div class="row">
        <form class="col s12" id="newSubject">
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="Digite um assunto" id="assunto" type="text" name="assunto">
                    <label for="assunto">Assunto *</label>
                </div>
            </div>
            <p class="right-align"><button id="salvar" type="submit" class="waves-effect waves-light btn">Cadastrar</button></p>
        </form>
    </div>
</div>

<script>

    $( "#newSubject" ).submit(function( event ) {
        event.preventDefault();
        var $form = $( this ),
            assunto = $form.find( "input[name='assunto']" ).val();

        var formData = JSON.stringify({ assunto: assunto });
        var posting = $.post( "<?= URL . '/novo-assunto' ?>", formData);
        posting.done(function( data ) {
            if (data.aviso == "Registro salvo com sucesso") {
                $("#salvar").addClass(" disabled");
                M.toast({html: data.aviso, classes: 'rounded'});
            } else {
                M.toast({html: data.aviso, classes: 'rounded'});
            }

        });
    });
</script>