<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="<?= URL . '/assets/css/materialize.min.css'?>">
    <title>Página não encontrada!</title>
    <style>
        body {
            display: flex;
            min-height: 100vh;
            flex-direction: column;
        }

        main {
            flex: 1 0 auto;
        }
    </style>
</head>
<body>
<nav>
    <div class="nav-wrapper red accent-4">
        <a href="#" class="brand-logo">Logo</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="<?= URL ?>">Página Inicial</a></li>
        </ul>
    </div>
</nav>
<main class="container-fluid">
    <div class="row">
        <div class="col s12">
            <h1>Ops: 404</h1><br>
            <h3>Página não encontrada</h3>
        </div>
    </div>
</main>
<footer class="page-footer red accent-4">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">Contrary to popular belief, Lorem Ipsum is not simply random text.</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Link's</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="<?= URL ?>">Página Inicial</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2021 Copyright
        </div>
    </div>
</footer>
</body>
</html>