
<footer class="page-footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col l6 s12">
                <h3 class="white-text">Footer Content</h3>
                <p class="grey-text text-lighten-4">Contrary to popular belief, Lorem Ipsum is not simply random text.</p>
            </div>
            <div class="col l4 offset-l2 s12" id="menuFooter">
                <h5 class="white-text">Link's</h5>
                <ul>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2021 Copyright
        </div>
    </div>
</footer>


<?php if (isset($_SESSION['username'])) : ?>
<div class="fixed-action-btn">
    <a class="btn-floating btn-large red tooltipped" data-position="left" data-tooltip="Menu">
        <i class="large material-icons">apps</i>
    </a>
    <ul>
        <li><a href="<?= URL . '/logout'?>" class="btn-floating blue tooltipped" data-position="left" data-tooltip="Sair (Deslogar)"><i class="material-icons">block</i></a></li>
    </ul>
</div>

<script>
    $(document).ready(function(){
        $('.fixed-action-btn').floatingActionButton();
        $('.tooltipped').tooltip();
    });
</script>

<?php endif; ?>

<script>
    $(document).ready(function() {
        $('#mobile-demo').sidenav();
    });
</script>
</body>
</html>