<footer class="page-footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col l6 s12">
                <h3 class="white-text">Footer Content</h3>
                <p class="grey-text text-lighten-4">Contrary to popular belief, Lorem Ipsum is not simply random text.</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Link's</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="<?= URL ?>">Página Inicial</a></li>
                    <li><a class="grey-text text-lighten-3" href="<?= URL . 'sobre' ?>">Quem somos</a></li>
                    <li><a class="grey-text text-lighten-3" href="<?= URL . 'login' ?>">Entrar</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2021 Copyright
        </div>
    </div>
</footer>
</body>
</html>