<nav>
    <div class="nav-wrapper">
        <div class="col s12">
            <a href="#!" class="breadcrumb"> </a>
            <a href="#!" class="breadcrumb">Nova Banca</a>
        </div>
    </div>
</nav>
<main class="container">
    <br>
    <div class="row">
        <form class="col s12" id="newSubject">
            <div class="row">
                <div class="input-field col s12">
                    <input placeholder="Digite o nome da banca" id="banca" type="text" name="banca">
                    <label for="banca">Banca *</label>
                </div>
            </div>
            <p class="right-align"><button id="salvar" type="submit" class="waves-effect waves-light btn">Cadastrar</button></p>
        </form>
    </div>
</main>

<script>

    $( "#newSubject" ).submit(function( event ) {
        event.preventDefault();
        var $form = $( this ),
            banca = $form.find( "input[name='banca']" ).val();

        var formData = JSON.stringify({ banca: banca });
        var posting = $.post( "<?= URL . '/nova-banca' ?>", formData);
        posting.done(function( data ) {
            if (data.aviso == "Registro salvo com sucesso") {
                $("#salvar").addClass(" disabled");
                M.toast({html: data.aviso, classes: 'rounded'});
            } else {
                M.toast({html: data.aviso, classes: 'rounded'});
            }

        });
    });
</script>