<nav>
    <div class="nav-wrapper">
        <div class="col s12">
            <a href="#!" class="breadcrumb"> </a>
            <a href="#!" class="breadcrumb">Editar Banca</a>
        </div>
    </div>
</nav>
<main class="container">
    <br>
    <div class="row">
        <form class="col s12" id="edit">
            <input type="hidden" name="id" value="<?= $data['id'] ?>">
            <div class="row">
                <div class="input-field col s12">
                    <input id="banca" type="text" name="banca" value="<?= $data['banca'] ?>">
                    <label for="banca">Banca *</label>
                </div>
            </div>
            <p class="right-align"><button id="salvar" type="submit" class="waves-effect waves-light btn">Atualizar</button></p>
        </form>
    </div>
</main>

<script>

    $( "#edit" ).submit(function( event ) {
        event.preventDefault();
        var $form = $( this ),
            id = $form.find( "input[name='id']" ).val(),
            banca = $form.find( "input[name='banca']" ).val();

        var formData = JSON.stringify({ id: id, banca: banca });
        var posting = $.post( "<?= URL . '/update-jury' ?>", formData);
        posting.done(function( data ) {
            if (data.aviso == 'Registro salvo com sucesso') {
                M.toast({html: data.aviso, classes: 'rounded'});
                setTimeout(function() {
                    window.location.href = "<?= URL ?>/banca/gerenciar";
                }, 1000);

            } else {
                M.toast({html: data, classes: 'rounded'});
            }

        });
    });
</script>